name: Update Solutions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update Wordle Solutions
      run: python update_wordle_solutions.py

    - name: Update Connections Solutions
      run: python update_connections.py

    - name: Commit and push if it changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add ./solutions/wordle_solutions.json
        git add ./solutions/connections_solutions.json
        git commit -m "Update solutions"
        git push